// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AvalancheDbContext))]
    [Migration("20240615134646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.AvalancheData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DataId"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AirTemperatureEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AirTemperatureMorning")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageTemperatureDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageTemperatureDecade")
                        .HasColumnType("numeric");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precipitation")
                        .HasColumnType("numeric");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SnowDepthAverageEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SnowDepthAverageMorning")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SnowDepthMaxEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SnowDepthMaxMorning")
                        .HasColumnType("numeric");

                    b.Property<string>("WeatherEvening")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeatherMorning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DataId");

                    b.HasIndex("RegionId");

                    b.ToTable("AvalancheData");
                });

            modelBuilder.Entity("WebApp.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("WebApp.Models.AvalancheData", b =>
                {
                    b.HasOne("WebApp.Models.Region", "Region")
                        .WithMany("AvalancheData")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WebApp.Models.Region", b =>
                {
                    b.Navigation("AvalancheData");
                });
#pragma warning restore 612, 618
        }
    }
}
